language: java

jdk: oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_858960957898_key -iv $encrypted_858960957898_iv -in client-secret.json.enc -out client-secret.json -d
  - gcloud auth activate-service-account --key-file client-secret.json

#install:
#  # Set the correct project to deploy to
#  - gcloud config set project soa-group-7-174
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

deploy:
  provider: gae
  keyfile: client-secret.json
  project: soa-group-7-174

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce